### ISSUE TITLE
Change user input name from 'Nutrition Target' to 'Type of Diet' in UI

### ISSUE THREAD

**Issue by ShariarImroze** [jistiak/aika#8]
Please kindly check the name of the option in UI. Nutrition and Diet are two separate things and we should use Diet.

**Comment by jistiak** [comment]
Have you tested if changing the terms in the prompt produces better results? Or is it just for decorative purpose?

**Comment by ShariarImroze** [comment]
I didn't test it. Mostly decorative.

**Comment by jistiak** [comment]
Okay, I will test it and update the terms.
